# Generated by Django 4.2.5 on 2023-10-17 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='players',
            name='email',
        ),
    ]
